s=set()
n1=int(input("Enter the any  number: "))
s.add(int(n1))
n2=int(input("Enter the any number: "))
s.add(int(n2))
n3=int(input("Enter the any number: "))
s.add(int(n3))
n4=int(input("Enter the any number: "))
s.add(int(n4))
n5=int(input("Enter the any number: "))
s.add(int(n5))
n6=int(input("Enter the any number: "))
s.add(int(n6))
n7=int(input("Enter the any number: "))
s.add(int(n7))
print(s)

